# Generated by Django 4.2.23 on 2025-08-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('homepage', models.URLField(blank=True)),
                ('rss_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('뉴스', '뉴스'), ('정책', '정책'), ('생활', '생활'), ('정보', '정보')], default='뉴스', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='community.newssource')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['-published_at'], name='community_n_publish_cd4474_idx'), models.Index(fields=['source', '-published_at'], name='community_n_source__a2aa37_idx'), models.Index(fields=['category'], name='community_n_categor_b14ddb_idx')],
            },
        ),
    ]
