# Generated by Django 4.2.23 on 2025-08-15 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_criteria', models.JSONField(default=dict, help_text='비교 기준 (예: 가격, 위치, 면적 등)')),
                ('analysis_summary', models.TextField(help_text='AI 분석 요약')),
                ('detailed_comparison', models.JSONField(default=dict, help_text='상세 비교 분석')),
                ('recommendation', models.CharField(help_text='AI 추천 (room_a 또는 room_b)', max_length=50)),
                ('reasoning', models.TextField(help_text='추천 이유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_reports_as_a', to='rooms.room')),
                ('room_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_reports_as_b', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'room_a', 'room_b')},
            },
        ),
    ]
